name: 'Convert and Push Test Report to S3'
description: 'Convert JUnit XML to HTML, rename the file with current date, and push to S3'
author: 'Berdan Çağlar Aydın'
branding:
  icon: 'upload-cloud'
  color: 'orange'
inputs:
  s3-bucket-base-path:
    description: 'Base path of the S3 bucket'
    required: true
  s3-path:
    description: 'Path within the S3 bucket'
    required: true
  version:
    description: 'Version identifier'
    required: false
    default: ${{ github.ref_name }}
  test-report-filename:
    description: 'Filename of the JUnit XML test report'
    required: false
    default: test_report.xml
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.s3-bucket-base-path }} 
    - ${{ inputs.s3-path }} 
    - ${{ inputs.version }} 
    - ${{ inputs.test-report-filename }}

